"""test column add

Revision ID: 1255e7b507fc
Revises: 3c1765dd1b6e
Create Date: 2013-06-16 14:48:24.019248

"""

# revision identifiers, used by Alembic.
revision = '1255e7b507fc'
down_revision = '3c1765dd1b6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test_col', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test_col')
    ### end Alembic commands ###
