"""changed_table_name123

Revision ID: 15b342caf71a
Revises: 2bcfb38713d8
Create Date: 2013-06-16 14:32:11.507189

"""

# revision identifiers, used by Alembic.
revision = '15b342caf71a'
down_revision = '2bcfb38713d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
