"""changed_table_name

Revision ID: 1b7993c207ab
Revises: 5985046c3f12
Create Date: 2013-06-16 14:31:38.354079

"""

# revision identifiers, used by Alembic.
revision = '1b7993c207ab'
down_revision = '5985046c3f12'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
