"""userkey add

Revision ID: 1f791bd5942c
Revises: 96ea71607fc
Create Date: 2013-08-12 09:23:17.568533

"""

# revision identifiers, used by Alembic.
revision = '1f791bd5942c'
down_revision = '96ea71607fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercomplete', sa.Column('user_key', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercomplete', 'user_key')
    ### end Alembic commands ###
