"""interestedin add

Revision ID: 2416bb81eefc
Revises: 55a647e64bb7
Create Date: 2013-08-13 00:12:08.271746

"""

# revision identifiers, used by Alembic.
revision = '2416bb81eefc'
down_revision = '55a647e64bb7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercomplete', sa.Column('interested_in', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercomplete', 'interested_in')
    ### end Alembic commands ###
