"""first version

Revision ID: 2508c3ef4e58
Revises: 1255e7b507fc
Create Date: 2013-06-16 15:23:08.824108

"""

# revision identifiers, used by Alembic.
revision = '2508c3ef4e58'
down_revision = '1255e7b507fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('profile_pic_url', sa.String(length=300), nullable=True),
    sa.Column('profile_album', sa.PickleType(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('work_position', sa.String(length=200), nullable=True),
    sa.Column('work_employer', sa.String(length=200), nullable=True),
    sa.Column('work_startdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'user', u'test_col')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column(u'test_col', sa.VARCHAR(length=10), nullable=True))
    op.drop_table('profile_data')
    ### end Alembic commands ###
