"""changed_table_name

Revision ID: 27d2275e606c
Revises: e718a70e1d2
Create Date: 2013-06-16 14:07:14.769431

"""

# revision identifiers, used by Alembic.
revision = '27d2275e606c'
down_revision = 'e718a70e1d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
