"""changed_table_name

Revision ID: 2b26f385f3c5
Revises: 318c5db94c46
Create Date: 2013-06-16 14:30:34.685450

"""

# revision identifiers, used by Alembic.
revision = '2b26f385f3c5'
down_revision = '318c5db94c46'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
