"""changed_table_name

Revision ID: 2bcfb38713d8
Revises: 1b7993c207ab
Create Date: 2013-06-16 14:31:59.084663

"""

# revision identifiers, used by Alembic.
revision = '2bcfb38713d8'
down_revision = '1b7993c207ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
