"""remove likes

Revision ID: 2c2756d1f1dd
Revises: 3d32d7a64003
Create Date: 2013-08-13 11:25:53.496969

"""

# revision identifiers, used by Alembic.
revision = '2c2756d1f1dd'
down_revision = '3d32d7a64003'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercomplete', u'likes_dummy')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercomplete', sa.Column(u'likes_dummy', sa.VARCHAR(length=2000), nullable=True))
    ### end Alembic commands ###
