"""first draft of models

Revision ID: 2d17a2d36352
Revises: 2508c3ef4e58
Create Date: 2013-06-17 00:48:26.811519

"""

# revision identifiers, used by Alembic.
revision = '2d17a2d36352'
down_revision = '2508c3ef4e58'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_data', sa.Column('education_dummy', sa.String(length=1000), nullable=True))
    op.add_column('profile_data', sa.Column('hometown_location_latlong', sa.PickleType(), nullable=True))
    op.add_column('profile_data', sa.Column('hometown_location_country', sa.String(length=80), nullable=True))
    op.add_column('profile_data', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('profile_data', sa.Column('current_location_city', sa.String(length=80), nullable=True))
    op.add_column('profile_data', sa.Column('current_location_state', sa.String(length=80), nullable=True))
    op.add_column('profile_data', sa.Column('current_location_name', sa.String(length=80), nullable=True))
    op.add_column('profile_data', sa.Column('work', sa.PickleType(), nullable=True))
    op.add_column('profile_data', sa.Column('current_location_country', sa.String(length=80), nullable=True))
    op.add_column('profile_data', sa.Column('hometown_location_city', sa.String(length=80), nullable=True))
    op.add_column('profile_data', sa.Column('work_dummy', sa.String(length=1000), nullable=True))
    op.add_column('profile_data', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.add_column('profile_data', sa.Column('hometown_location_state', sa.String(length=80), nullable=True))
    op.add_column('profile_data', sa.Column('likes', sa.PickleType(), nullable=True))
    op.add_column('profile_data', sa.Column('current_location_latlong', sa.PickleType(), nullable=True))
    op.add_column('profile_data', sa.Column('watched', sa.PickleType(), nullable=True))
    op.add_column('profile_data', sa.Column('likes_dummy', sa.String(length=2000), nullable=True))
    op.add_column('profile_data', sa.Column('education', sa.PickleType(), nullable=True))
    op.add_column('profile_data', sa.Column('interested_in', sa.String(length=80), nullable=True))
    op.add_column('profile_data', sa.Column('wants_to', sa.PickleType(), nullable=True))
    op.drop_column('profile_data', u'work_startdate')
    op.drop_column('profile_data', u'work_employer')
    op.drop_column('profile_data', u'work_position')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_data', sa.Column(u'work_position', sa.VARCHAR(length=200), nullable=True))
    op.add_column('profile_data', sa.Column(u'work_employer', sa.VARCHAR(length=200), nullable=True))
    op.add_column('profile_data', sa.Column(u'work_startdate', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('profile_data', 'wants_to')
    op.drop_column('profile_data', 'interested_in')
    op.drop_column('profile_data', 'education')
    op.drop_column('profile_data', 'likes_dummy')
    op.drop_column('profile_data', 'watched')
    op.drop_column('profile_data', 'current_location_latlong')
    op.drop_column('profile_data', 'likes')
    op.drop_column('profile_data', 'hometown_location_state')
    op.drop_column('profile_data', 'birthday')
    op.drop_column('profile_data', 'work_dummy')
    op.drop_column('profile_data', 'hometown_location_city')
    op.drop_column('profile_data', 'current_location_country')
    op.drop_column('profile_data', 'work')
    op.drop_column('profile_data', 'current_location_name')
    op.drop_column('profile_data', 'current_location_state')
    op.drop_column('profile_data', 'current_location_city')
    op.drop_column('profile_data', 'last_updated')
    op.drop_column('profile_data', 'hometown_location_country')
    op.drop_column('profile_data', 'hometown_location_latlong')
    op.drop_column('profile_data', 'education_dummy')
    ### end Alembic commands ###
