"""changed_table_name

Revision ID: 318c5db94c46
Revises: 47a9b4a3fc08
Create Date: 2013-06-16 14:29:08.503549

"""

# revision identifiers, used by Alembic.
revision = '318c5db94c46'
down_revision = '47a9b4a3fc08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
