"""add likes

Revision ID: 31efed7073ec
Revises: 2c2756d1f1dd
Create Date: 2013-08-13 11:26:12.418121

"""

# revision identifiers, used by Alembic.
revision = '31efed7073ec'
down_revision = '2c2756d1f1dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercomplete', sa.Column('likes_dummy', sa.String(length=3000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercomplete', 'likes_dummy')
    ### end Alembic commands ###
