"""rm edu name

Revision ID: 36b72423223
Revises: 47869dd4522e
Create Date: 2013-07-14 22:08:59.147933

"""

# revision identifiers, used by Alembic.
revision = '36b72423223'
down_revision = '47869dd4522e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercomplete', u'education_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercomplete', sa.Column(u'education_name', sa.VARCHAR(length=300), nullable=True))
    ### end Alembic commands ###
