"""create usercomplete

Revision ID: 3d32d7a64003
Revises: 3f7b41f2a909
Create Date: 2013-08-13 11:13:11.136745

"""

# revision identifiers, used by Alembic.
revision = '3d32d7a64003'
down_revision = '3f7b41f2a909'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercomplete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('fb_uid', sa.String(length=30), nullable=True),
    sa.Column('user_key', sa.String(length=50), nullable=True),
    sa.Column('profile_pic_url', sa.String(length=300), nullable=True),
    sa.Column('profile_album', sa.PickleType(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('work', sa.PickleType(), nullable=True),
    sa.Column('current_location_name', sa.String(length=80), nullable=True),
    sa.Column('current_location_dummy', sa.String(length=300), nullable=True),
    sa.Column('current_location_latlong', sa.PickleType(), nullable=True),
    sa.Column('hometown_location_name', sa.String(length=80), nullable=True),
    sa.Column('hometown_location_dummy', sa.String(length=300), nullable=True),
    sa.Column('hometown_location_latlong', sa.PickleType(), nullable=True),
    sa.Column('birthday', sa.String(length=20), nullable=True),
    sa.Column('birthday_dformat', sa.DateTime(), nullable=True),
    sa.Column('interested_in', sa.String(length=30), nullable=True),
    sa.Column('education', sa.PickleType(), nullable=True),
    sa.Column('likes_dummy', sa.String(length=2000), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('relationship_status', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usercomplete')
    ### end Alembic commands ###
