"""changed column conditions

Revision ID: 413c841c1e4
Revises: 53173a3aba50
Create Date: 2013-06-16 14:44:25.401570

"""

# revision identifiers, used by Alembic.
revision = '413c841c1e4'
down_revision = '53173a3aba50'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
