"""added width height

Revision ID: 423e72cf10eb
Revises: 113a2223bcc2
Create Date: 2013-07-09 10:46:45.670245

"""

# revision identifiers, used by Alembic.
revision = '423e72cf10eb'
down_revision = '113a2223bcc2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_data', u'width')
    op.drop_column('profile_data', u'height')
    op.add_column('usercomplete', sa.Column('width', sa.String(length=4), nullable=True))
    op.add_column('usercomplete', sa.Column('height', sa.String(length=4), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercomplete', 'height')
    op.drop_column('usercomplete', 'width')
    op.add_column('profile_data', sa.Column(u'height', sa.VARCHAR(length=4), nullable=True))
    op.add_column('profile_data', sa.Column(u'width', sa.VARCHAR(length=4), nullable=True))
    ### end Alembic commands ###
