"""add likes ids

Revision ID: 45a547d8ba1f
Revises: 4e2a979bfc32
Create Date: 2013-08-19 02:17:00.854749

"""

# revision identifiers, used by Alembic.
revision = '45a547d8ba1f'
down_revision = '4e2a979bfc32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercomplete', sa.Column('likes_dummy_ids', sa.PickleType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercomplete', 'likes_dummy_ids')
    ### end Alembic commands ###
