"""add edu work name

Revision ID: 47869dd4522e
Revises: 423e72cf10eb
Create Date: 2013-07-14 22:01:11.967486

"""

# revision identifiers, used by Alembic.
revision = '47869dd4522e'
down_revision = '423e72cf10eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercomplete', sa.Column('work_name', sa.String(length=300), nullable=True))
    op.add_column('usercomplete', sa.Column('education_name', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercomplete', 'education_name')
    op.drop_column('usercomplete', 'work_name')
    ### end Alembic commands ###
