"""changed_table_name

Revision ID: 47a9b4a3fc08
Revises: 27d2275e606c
Create Date: 2013-06-16 14:07:59.251986

"""

# revision identifiers, used by Alembic.
revision = '47a9b4a3fc08'
down_revision = '27d2275e606c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
