"""add width height

Revision ID: 4e2a979bfc32
Revises: 31efed7073ec
Create Date: 2013-08-15 12:02:03.951324

"""

# revision identifiers, used by Alembic.
revision = '4e2a979bfc32'
down_revision = '31efed7073ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercomplete', sa.Column('width', sa.String(length=4), nullable=True))
    op.add_column('usercomplete', sa.Column('height', sa.String(length=4), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercomplete', 'height')
    op.drop_column('usercomplete', 'width')
    ### end Alembic commands ###
