"""added votes

Revision ID: 4e6ec201efc9
Revises: 78c329dd819
Create Date: 2013-06-18 11:17:17.372358

"""

# revision identifiers, used by Alembic.
revision = '4e6ec201efc9'
down_revision = '78c329dd819'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_data', sa.Column('votes', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_data', 'votes')
    ### end Alembic commands ###
