"""add work1 and edu1

Revision ID: 507cc7de5a5d
Revises: 50373b63c9bd
Create Date: 2013-09-21 18:16:00.175576

"""

# revision identifiers, used by Alembic.
revision = '507cc7de5a5d'
down_revision = '50373b63c9bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercomplete', sa.Column('work1', sa.PickleType(), nullable=True))
    op.add_column('usercomplete', sa.Column('education1', sa.PickleType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercomplete', 'education1')
    op.drop_column('usercomplete', 'work1')
    ### end Alembic commands ###
