"""birthday remove

Revision ID: 524958de1cf
Revises: 1f791bd5942c
Create Date: 2013-08-12 09:55:30.013085

"""

# revision identifiers, used by Alembic.
revision = '524958de1cf'
down_revision = '1f791bd5942c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercomplete', u'birthday')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercomplete', sa.Column(u'birthday', postgresql.TIMESTAMP(), nullable=True))
    ### end Alembic commands ###
