"""birthday add

Revision ID: 55a647e64bb7
Revises: 524958de1cf
Create Date: 2013-08-12 09:55:44.454900

"""

# revision identifiers, used by Alembic.
revision = '55a647e64bb7'
down_revision = '524958de1cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercomplete', sa.Column('birthday', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercomplete', 'birthday')
    ### end Alembic commands ###
