"""changed_table_name

Revision ID: 5985046c3f12
Revises: 2b26f385f3c5
Create Date: 2013-06-16 14:30:54.631500

"""

# revision identifiers, used by Alembic.
revision = '5985046c3f12'
down_revision = '2b26f385f3c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
