"""adding hometown location name

Revision ID: 78c329dd819
Revises: 2d17a2d36352
Create Date: 2013-06-17 02:20:34.361682

"""

# revision identifiers, used by Alembic.
revision = '78c329dd819'
down_revision = '2d17a2d36352'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_data', sa.Column('hometown_location_name', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_data', 'hometown_location_name')
    ### end Alembic commands ###
