"""add edu name

Revision ID: 893781361d8
Revises: 36b72423223
Create Date: 2013-07-14 22:10:54.701516

"""

# revision identifiers, used by Alembic.
revision = '893781361d8'
down_revision = '36b72423223'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercomplete', sa.Column('education_name', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercomplete', 'education_name')
    ### end Alembic commands ###
